### ISSUE TITLE
Filter only recources in one or several CloudFormation stacks (--stack-names option)

### ISSUE THREAD

**Issue by dmartsynkevych** [duo-labs/cloudmapper#75]
This is an awesome project. Bravo.
We have AWS accounts with many projects and huge number of resources in each of them. Current filters do not allow to ignore 99% resources and we have crowd of resources mixed from different projects. Web server getting overloaded very slow. It takes couple of minutes to generate web page in browser and result is not informative.
Is it possible do add filter like "--stack-names" that will filter resources only from one/two/three... CloudFormation stacks. Stacks usually have 5-25 resources and visualisation will be much better.
In this case we can start many web servers on different ports and see each project on personal port.
Thank you for you fantastic work.

**Comment by 0xdabbad00** [comment]
Do CloudFormation stack resources receive specific tags? If so the work for #36 may resolve this.

**Comment by dmartsynkevych** [comment]
1. --collapse-by-tag will not help.
2. Not all resources have tags. But it will work as workaround.
3. Also make sure that new filter "--tags" will work with keys that contains symbol ":" like:
aws:cloudformation:stack-name
Thank you.

**Comment by 0xdabbad00** [comment]
I think to really solve this I would need to make calls to `aws cloudformation describe-stack-resources` and then correlate those resources with the resources found in the account.  I currently do not have any experience working with CloudFormation, so this seems like a big undertaking for me currently, although someone with more experience with CloudFormation might have easier success.

**Comment by dmartsynkevych** [comment]
> I would need to make calls to "aws cloudformation describe-stack-resources"

Right.

> I currently do not have any experience working with CloudFormation

It is very easy. Just 3 steps:
1. Save the following code in YAML format as test2.template file:
```
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack for Test2 project

Resources:

  Test2Lb:
    Type: "AWS::ElasticLoadBalancing::LoadBalancer"
    Properties:
      LoadBalancerName: test2
      Listeners:
        - LoadBalancerPort: 80
          Protocol: HTTP
          InstancePort: 80
          InstanceProtocol: HTTP
      Scheme: internal
      Subnets:
        - subnet-xxxxxx                  # <------ CHANGE IT

  Test2Lc:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      ImageId: ami-97785bed              # <------ CHANGE IT
      InstanceType: t2.micro
      KeyName: admin                     # <------ CHANGE IT

  Test2Asg:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      HealthCheckGracePeriod: 300
      HealthCheckType: EC2
      LaunchConfigurationName:
        Ref: Test2Lc
      LoadBalancerNames:
        - Ref: Test2Lb
      MinSize: 2
      MaxSize: 2
      VPCZoneIdentifier:
        - subnet-xxxxxx                  # <------ CHANGE IT
```
2. Change 4 parameters like Subnets, AMIID, KeyName according your environment.
3. Run:
`aws cloudformation create-stack --stack-name test2 --template-body file://test2.template`
This command create simple stack with name test2. Stack contains:

- LoadBalancer
- AutoScalingGroup
- LaunchConfiguration

AutoScalingGroup will contains 2 instances.
Now you can see/edit/delete stack into Amazon web console in CloudFormation section.
and make CloudMapper experiments on this stack :)
