### ISSUE TITLE
Counting DynamoDB Tables

### ISSUE THREAD

**Issue by ps9786** [duo-labs/cloudmapper#766]
Hi, I have searched the code and the yaml's but cant see any way to count the number of DynamoDB tables. Do I need to add a custom scipt?

Apologies if this has been asked before I did search for DynamoDB in the issues.

**Comment by 0xdabbad00** [comment]
CloudMapper does not currently collect info about DynamoDB tables, as there hasn't been anything I know to audit about them and haven't had another use for them within CloudMapper.  You would need to add lines to the `collect` configuration: https://github.com/duo-labs/cloudmapper/blob/main/collect_commands.yaml

And then add lines to the `stats` configuration:
https://github.com/duo-labs/cloudmapper/blob/main/stats_config.yaml

If you want to send a PR for this I'll get it merged.

**Comment by ps9786** [comment]
Thanks for the reply and info.

I successfully managed to get a count of tables but when trying to get the "Arn" for the table in order to get the Tags, I am failing.

I have this in collect

```
- Service: dynamodb
  Request: list-tables
- Service: dynamodb
  Request: describe-table
  Parameters:
  - Name: TableName
    Value: dynamodb-list-tables.json |.TableNames[]?|.
```

I can see the table names when using jq, what am I doing wrong?

Thank you.

Paul
